Repository activemerchant/active_merchant, pull requests merged in 2018-08, with the labels that each got.

#2953 BlueSnap: Add StoreCard Field
  CHANGELOG
  lib/active_merchant/billing/gateways/blue_snap.rb
  test/unit/gateways/blue_snap_test.rb
Labels: improvement

#2959 Paymentez: add support for partial refunds
  CHANGELOG
  lib/active_merchant/billing/gateways/paymentez.rb
  test/remote/gateways/remote_paymentez_test.rb
  test/unit/gateways/paymentez_test.rb
Labels: gateway/feature

#2952 Allow setting CAPTURECOMPLETE on Payflow capture transactions
  lib/active_merchant/billing/gateways/payflow/payflow_common_api.rb
  lib/active_merchant/billing/gateways/payflow_express.rb
  test/remote/gateways/remote_payflow_test.rb
Labels: improvement

#2951 Adyen: Add RecurringProcessingModel
  CHANGELOG
  lib/active_merchant/billing/gateways/adyen.rb
  test/remote/gateways/remote_adyen_test.rb
  test/unit/gateways/adyen_test.rb
Labels: improvement

#2961 Optimal: document additional country support
  CHANGELOG
  lib/active_merchant/billing/gateways/optimal_payment.rb
Labels: gateway/fix

#2962 Fix typo in gateway generator
  CHANGELOG
  generators/gateway/gateway_generator.rb
Labels: improvement

#2968 Adyen: add Maestro and Electron support
  CHANGELOG
  lib/active_merchant/billing/gateways/adyen.rb
  test/remote/gateways/remote_adyen_test.rb
  test/unit/gateways/adyen_test.rb
Labels: gateway/feature
