Repository activemerchant/active_merchant, pull requests merged in 2018-06, with the labels that each got.

#2902 Remove redundant lines from .travis.yml
  .travis.yml
Labels: improvement, technical debt

#2894 Add RuboCop support
  .rubocop.yml
  .rubocop_todo.yml
  Gemfile
  Rakefile
  lib/active_merchant/billing/credit_card_formatting.rb
  lib/active_merchant/billing/gateways/cashnet.rb
  lib/active_merchant/billing/gateways/cecabank.rb
  lib/active_merchant/billing/gateways/culqi.rb
  test/unit/gateways/braintree_blue_test.rb
  test/unit/gateways/stripe_test.rb
Labels: technical debt

#2772 Visanet Peru: Refund on unsettled transactions
  CHANGELOG
  lib/active_merchant/billing/gateways/visanet_peru.rb
  test/fixtures.yml
  test/remote/gateways/remote_visanet_peru_test.rb
  test/unit/gateways/visanet_peru_test.rb
Labels: gateway/feature

#2807 Remove iDeal references
  CHANGELOG
  lib/active_merchant/billing/gateways/ideal/ideal_base.rb
  lib/active_merchant/billing/gateways/ideal/ideal_rabobank.pem
  lib/active_merchant/billing/gateways/ideal/ideal_response.rb
  lib/active_merchant/billing/gateways/ideal_rabobank.rb
  test/fixtures.yml
  test/remote/gateways/remote_ideal_rabobank_test.rb
  test/unit/gateways/ideal_rabobank_test.rb
Labels: gateway/fix

#2909 Default SSL min_version to TLS 1.1 to comply with PCI DSS deadline
  CHANGELOG
  lib/active_merchant/connection.rb
  lib/active_merchant/posts_data.rb
  test/unit/connection_test.rb
Labels: compatibility, improvement, security
