Repository activemerchant/active_merchant, pull requests merged in 2018-09, with the labels that each got.

#2980 Reflect correct test mode in Braintree responses
  CHANGELOG
  lib/active_merchant/billing/gateways/braintree_blue.rb
  test/unit/gateways/braintree_blue_test.rb
Labels: gateway/fix

#2988 Assume CC numbers are strings
  lib/active_merchant/billing/credit_card_methods.rb
Labels: compatibility, technical debt

#2999 Enable Carnet for Conekta and Openpay
  CHANGELOG
  lib/active_merchant/billing/gateways/conekta.rb
  lib/active_merchant/billing/gateways/openpay.rb
Labels: compatibility
